def classes():
    return ['Pharmacology for AT',
    'Human Nutrition',
    'Comp Networks & Security',
    'Principles of Counseling',
    'Intro to Human Com',
    'Mass Comm',
    'Public Relations',
    'Com Relations in Orgs',
    'Survey of Com Research',
    'Technology and Society',
    'Intro Comps & Office',
    'Intro to Microsoft Excel',
    'Intro to Microsoft Acces',
    'Computer Science II',
    'Computer Science II Lab',
    'Logic for Comp Scientist',
    'Comp NW Culture: Music',
    'Comp NW Social Systems',
    'Economic Life',
    'Principle Microeconomics',
    'The Global Economy',
    'Exceptionalities',
    'Continuation Prep Math',
    'Internship I',
    'Engineering Fundamentals',
    'Acad. Writing & Reading',
    'Research Writing',
    'Business Writing',
    'British Texts',
    'Post-Colonial Texts',
    'Technical Writing',
    'Intro to Poetry Writing',
    'Intro to Food Science',
    'Farm Business Management',
    'Food Plant San and HACCP',
    'Food Microbiology',
    'Food Chem and Analysis',
    'Food Laws and Regulation',
    'West. Civ. to 1500',
    'West & World since 1500',
    'Tech Based Ventures',
    'I&E Seminar Series',
    'Illustration',
    'E-Commerce Advertising',
    'Psychology of Sport',
    'Human Resources Mgt',
    'Internship in IS',
    'Principles of Marketing',
    'Music Listening',
    'Music in Western Culture',
    'Patho Across Lifespan',
    'Found of Research & EBP',
    'Transition Role Prof Nur',
    'Nur Role for Unlicensed',
    'Nursing',
    'Ldrship & Mngmt',
    'Colab Impv Pat Hlth Outc',
    'Honors Project Seminar',
    'Professional Devel II',
    'Professional Devel IV',
    'Integ Office Software',
    'Admin Office Management',
    'Self as Leader',
    'Leading Change',
    'Political Life',
    'International Politics',
    'Cyber Crime',
    'Topics Criminal Justice',
    'Intro to Psychology Lab',
    'Psych of Disabilities',
    'Childhood & Adolescence',
    'Psychology Men and Women',
    'Forensic Psychology',
    'Honors Pharmacology Res',
    'Drug & Alcohol Abuse',
    'Rehab Internship',
    'Educational Interpreting',
    'SLI Senior Capstone',
    'Intro to Sociology',
    'Grow/Change Urb Society',
    'Womens Studies',
    'Ethics in Engineering',
    'Adv Ergon',
    'Lean Proc Impr Engr',
    'Comp Networks & Security Lab',
    'Host Computer Security',
    'Information Security',
    'Adv. Comp. Networks',
    'CNL Theory and Practice',
    'Techniques of Counseling',
    'Stats Res for Counseling',
    'Group Background &Theory',
    'Asses & Eval in Counsel',
    'Marriage',
    'Coun Life-Span Develop',
    'Pro Orient Eth & Leg Iss',
    'Multicultural Counseling',
    'Prin & Prac of Schl Coun',
    'Human Sexuality Counsel',
    'Clin Assess in Cnl Prac',
    'Diagnosis Clin Cnl Prac',
    'Comp Sys & Structures',
    'Functional & Logic Prog.',
    'Information Retrieval',
    'Eco Applica Internet II',
    'Read & Lit II: Int Spec',
    'Teach in the Amer Ed Sys',
    'Action Research: Science',
    'Diagnosis and Assessment',
    'Pract I: Intervention',
    'Literacy Inquiry Project',
    'Ldrshp Schl Improvement',
    'Analysis of Teaching',
    'Tchr Ldr Masters Exit',
    'Data Driven Decisions',
    'Advanced Ed Measurement',
    'Bldg-Level Leadership',
    'Bldg Budget',
    'Principal Practicum',
    'Adv Tchr Ldr Seminar',
    'Pol & Soc Contexts',
    'Organizational Behavior',
    'Superintendent Practicum']