def majors():
	return ['Biology',
	'Chemistry',
	'Mathematics',
	'Political Science',
	'Psychology',
	'Social Sciences',
	'Social Work',
	'Sociology',
	'Speech Pathology',
	'Accounting',
	'Finance' ,
	'Management',
	'Management Information Systems',
	'Marketing',
	'Family & Consumer Sciences',
	'Child & Family Studies',
	'Dietetics',
	'Retail Merchandising',
	'Art',
	'Ceramics',
	'Drawing',
	'Graphic Design',
	'Painting',
	'Photography',
	'Printmaking',
	'Sculpture',
	'New Media',
	'Mass Communication',
	'Music',
	'Composition',
	'Instrumental Performance',
	'Organ Performance',
	'Piano Pedagogy',
	'Piano Performance',
	'Vocal Performance',
	'Theatre',
	'Acting',
	'Directing',
	'Design and Technology',
	'Musical Theater']