# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, validators=[posts.validators.min_validation])),
                ('brand_type', models.CharField(max_length=80, validators=[posts.validators.min_validation])),
                ('description', models.TextField(validators=[posts.validators.min_validation])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand_email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
    ]
